version: '3.8'
services:
  platformsqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
#    healthcheck:
#      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "http://localhost:1433", "-U", "sa", "-P", "pa55w0rd!", "-Q", "SELECT 1", "||", "exit 1"]
#      interval: 20s
#      timeout: 10s
#      retries: 10
  platformservice:
    image: alexanderivashkin1402/platformservice
    ports:
      - "8080:80"
    restart: always
    depends_on:
    - "platformsqlserver"
#      platformsqlserver:
#        condition: service_completed_successfully
#        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: Development
